name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: source/global.json
        
    - name: Restore dependencies
      run: dotnet restore source/WebApi/WebApi.csproj
    - name: Build
      run: dotnet build source/WebApi/WebApi.csproj --no-restore
    - name: Test
      run: dotnet test source/WebApi/WebApi.csproj --no-build --verbosity normal
